# Generated by Django 4.1.1 on 2023-03-07 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email_address', models.EmailField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='email address')),
                ('subject', models.TextField(max_length=150, verbose_name='subject')),
                ('messages', models.TextField(max_length=250)),
            ],
        ),
    ]
