# Generated by Django 4.1.1 on 2023-03-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_querymessage_created_at_querymessage_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querymessage',
            name='subject',
            field=models.CharField(max_length=150, verbose_name='subject'),
        ),
    ]
